packageExtensions:
  '@oclif/parser@*':
    dependencies:
      '@oclif/errors': '*'
  '@oclif/plugin-help@*':
    dependencies:
      '@oclif/errors': '*'

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.0.2.cjs
