name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v4
        with:
          path: ".yarn/cache\n.pnp.js"
          key: "yarn-berry-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: 'yarn-berry-'
      - name: Yarn Install
        run: yarn install --immutable
      - name: Build & Deploy Website
        env:
          GIT_USER: ${{ secrets.BOT_TOKEN }}
        run: |
          git config --global user.name "dti-github-bot"
          git config --global user.email "admin@cornelldti.org"
          yarn deploy
