name: continuous-deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Build & Deploy Website
        run: |
          git config --global user.name "deployment-bot"
          GIT_USER=x-access-token:${{ github.token }} yarn deploy
