name: continuous-deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Build & Deploy Website
        env:
          DEPLOY_GH_PAGE_TOKEN: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
        run: |
          git config --global user.name "deployment-bot"
          GIT_USER=$DEPLOY_GH_PAGE_TOKEN yarn workspace blog deploy
